import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:workers_hub/core/theme/app_theme.dart';
import 'package:workers_hub/features/splash/splash_screen.dart';
import 'package:workers_hub/core/services/notification_service.dart';

import 'firebase_options.dart'; // This will be generated by flutterfire configure

import 'package:provider/provider.dart';
import 'package:workers_hub/core/providers/theme_provider.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  // Initialize push notifications
  await NotificationService().init();

  runApp(
    MultiProvider(
      providers: [ChangeNotifierProvider(create: (_) => ThemeProvider())],
      child: const WorkersHubApp(),
    ),
  );
}

class WorkersHubApp extends StatelessWidget {
  const WorkersHubApp({super.key});

  @override
  Widget build(BuildContext context) {
    final themeProvider = Provider.of<ThemeProvider>(context);

    return MaterialApp(
      title: 'Workers Hub',
      debugShowCheckedModeBanner: false,
      theme: AppTheme.lightTheme,
      darkTheme: AppTheme.darkTheme,
      themeMode: themeProvider.themeMode,
      home: const SplashScreen(),
    );
  }
}
