import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:workers_hub/core/theme/app_theme.dart';
import 'package:workers_hub/features/splash/splash_screen.dart';
import 'package:workers_hub/core/services/auth_service.dart';
import 'package:workers_hub/features/auth/screens/role_based_home.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'firebase_options.dart'; // This will be generated by flutterfire configure

import 'package:provider/provider.dart';
import 'package:workers_hub/core/providers/theme_provider.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  // NOTE: This requires 'flutterfire configure' to be run by the user to generate firebase_options.dart
  // For now, we will handle the case where it might fail or use default if possible,
  // but standard practice implies the file exists.
  // Since I cannot run flutterfire configure interactively, I will assume the user has done it or will do it.
  // I'll wrap it in a try-catch to prevent app crash if not configured yet, for development safety.
  try {
    // Try using the generated firebase_options.dart
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
  } catch (e) {
    // If that fails (e.g. placeholder file), try native file (google-services.json)
    try {
      await Firebase.initializeApp();
    } catch (e2) {
      print('Firebase initialization failed: $e2');
    }
  }

  runApp(
    MultiProvider(
      providers: [ChangeNotifierProvider(create: (_) => ThemeProvider())],
      child: const WorkersHubApp(),
    ),
  );
}

class WorkersHubApp extends StatelessWidget {
  const WorkersHubApp({super.key});

  @override
  Widget build(BuildContext context) {
    final themeProvider = Provider.of<ThemeProvider>(context);

    return MaterialApp(
      title: 'Workers Hub',
      debugShowCheckedModeBanner: false,
      theme: AppTheme.lightTheme,
      darkTheme: AppTheme.darkTheme,
      themeMode: themeProvider.themeMode,
      home: StreamBuilder<User?>(
        stream: AuthService().authStateChanges,
        builder: (context, snapshot) {
          if (snapshot.connectionState == ConnectionState.waiting) {
            return const Scaffold(
              body: Center(child: CircularProgressIndicator()),
            );
          }
          if (snapshot.hasData) {
            // User is signed in.
            return const RoleBasedHome();
          }
          // User is not signed in
          return const SplashScreen();
        },
      ),
    );
  }
}
